services:
  - type: web
    name: immo-backend
    runtime: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: node dist/src/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
